# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rack' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'IQKeyboardManagerSwift', '4.0.8'
    pod 'SIAlertView'
    pod 'ActiveLabel'
    pod 'PeekView'
    pod 'AFNetworking', '~> 3.0'
    pod 'TTGSnackbar'
    pod 'NVActivityIndicatorView'
    
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'GoogleAnalytics'
	pod 'MBProgressHUD', '~> 1.0.0'
    pod 'TwitterKit'
    pod 'TMTumblrSDK'
    pod 'PinterestSDK'
    
  # Pods for Rack

end
